version: "3.8"
services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    networks:
      - pgadmin-local
    extra_hosts:
      tunnel-host: ${PGADMIN_PORT_FWD_IP:?}
    ports:
      - "127.0.0.1:5050:80"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data:

networks:
  pgadmin-local:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${PGADMIN_PORT_FWD_IP}/24
