apiVersion: apps/v1
kind: Deployment
metadata:
  name: floskl
  labels:
    app: floskl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: floskl
  template:
    metadata:
      labels:
        app: floskl

    spec:
        initContainers:
        - name: db-init
          image: harbor.floskl.life/common/floskl:1.0.0
          command: ['flask', '--app', 'floskl', 'init-db']
          envFrom:
          - configMapRef:
              name: floskl-config
          - secretRef:
              name: floskl-secrets

        containers:
        - name: floskl
          image: harbor.floskl.life/common/floskl:1.0.0
          envFrom:
          - configMapRef:
              name: floskl-config
          - secretRef:
              name: floskl-secrets

          resources:
            limits:
              memory: "128Mi"
              cpu: "30m"
