apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: joker
spec:
  replicas: 1  # <- How many Pods to create (scale up/down)
  selector:
    matchLabels:
      app: joker  # <- Which template below to use (only one in this case)
  template:
    metadata:
      labels:
        app: joker  # <- Matches the selector rule above

    # The part below follows the schema for Pod definitions
    spec: 
        containers:
        - name: joker
          image: ghcr.io/uivraeus/python-example:latest

          env:
          - name: PASSWORD  # <- not really used in the app but included as an example
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: PASSWORD
          - name: BG_COLOR
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: BG_COLOR
          - name: TEXT_COLOR
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: TEXT_COLOR
          - name: SERVER_HOST
            value: "0.0.0.0"  # <- always use this (no need to assign via ConfigMap)

          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
