apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
  - name: example
    image: harbor.floskl.life/common/cpp-example:1.0.0
    env:
    - name: APP_ITERATION_DELAY
      value: "7"
    resources:
      limits:
        memory: "128Mi"
        cpu: "20m"
